[debug]
# address = "192.168.1.70"
# address = "192.168.1.70"
address = "127.0.0.1"
port = 8000
workers = 1
keep_alive = 0
log_level = "normal"

[release]
address = "127.0.0.1"
port = 8000
workers = 12
keep_alive = 5
log_level = "critical"